// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/baan/baan.service.go

// Package mock_baan is a generated GoMock package.
package mock_baan

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apperror "github.com/isd-sgcu/rpkm67-gateway/apperror"
	dto "github.com/isd-sgcu/rpkm67-gateway/internal/dto"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FindAllBaan mocks base method.
func (m *MockService) FindAllBaan(req *dto.FindAllBaanRequest) (*dto.FindAllBaanResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllBaan", req)
	ret0, _ := ret[0].(*dto.FindAllBaanResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// FindAllBaan indicates an expected call of FindAllBaan.
func (mr *MockServiceMockRecorder) FindAllBaan(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllBaan", reflect.TypeOf((*MockService)(nil).FindAllBaan), req)
}

// FindOneBaan mocks base method.
func (m *MockService) FindOneBaan(req *dto.FindOneBaanRequest) (*dto.FindOneBaanResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneBaan", req)
	ret0, _ := ret[0].(*dto.FindOneBaanResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// FindOneBaan indicates an expected call of FindOneBaan.
func (mr *MockServiceMockRecorder) FindOneBaan(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneBaan", reflect.TypeOf((*MockService)(nil).FindOneBaan), req)
}
