// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/stamp/stamp.client.go

// Package mock_stamp is a generated GoMock package.
package mock_stamp

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/isd-sgcu/rpkm67-go-proto/rpkm67/backend/stamp/v1"
	grpc "google.golang.org/grpc"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FindByUserId mocks base method.
func (m *MockClient) FindByUserId(ctx context.Context, in *v1.FindByUserIdStampRequest, opts ...grpc.CallOption) (*v1.FindByUserIdStampResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByUserId", varargs...)
	ret0, _ := ret[0].(*v1.FindByUserIdStampResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockClientMockRecorder) FindByUserId(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockClient)(nil).FindByUserId), varargs...)
}

// StampByUserId mocks base method.
func (m *MockClient) StampByUserId(ctx context.Context, in *v1.StampByUserIdRequest, opts ...grpc.CallOption) (*v1.StampByUserIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StampByUserId", varargs...)
	ret0, _ := ret[0].(*v1.StampByUserIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StampByUserId indicates an expected call of StampByUserId.
func (mr *MockClientMockRecorder) StampByUserId(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StampByUserId", reflect.TypeOf((*MockClient)(nil).StampByUserId), varargs...)
}
