// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/group/group.service.go

// Package mock_group is a generated GoMock package.
package mock_group

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apperror "github.com/isd-sgcu/rpkm67-gateway/apperror"
	dto "github.com/isd-sgcu/rpkm67-gateway/internal/dto"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeleteMember mocks base method.
func (m *MockService) DeleteMember(req *dto.DeleteMemberGroupRequest) (*dto.DeleteMemberGroupResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMember", req)
	ret0, _ := ret[0].(*dto.DeleteMemberGroupResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// DeleteMember indicates an expected call of DeleteMember.
func (mr *MockServiceMockRecorder) DeleteMember(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMember", reflect.TypeOf((*MockService)(nil).DeleteMember), req)
}

// FindByToken mocks base method.
func (m *MockService) FindByToken(req *dto.FindByTokenGroupRequest) (*dto.FindByTokenGroupResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", req)
	ret0, _ := ret[0].(*dto.FindByTokenGroupResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockServiceMockRecorder) FindByToken(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockService)(nil).FindByToken), req)
}

// FindByUserId mocks base method.
func (m *MockService) FindByUserId(req *dto.FindByUserIdGroupRequest) (*dto.FindByUserIdGroupResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", req)
	ret0, _ := ret[0].(*dto.FindByUserIdGroupResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockServiceMockRecorder) FindByUserId(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockService)(nil).FindByUserId), req)
}

// Join mocks base method.
func (m *MockService) Join(req *dto.JoinGroupRequest) (*dto.JoinGroupResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", req)
	ret0, _ := ret[0].(*dto.JoinGroupResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// Join indicates an expected call of Join.
func (mr *MockServiceMockRecorder) Join(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockService)(nil).Join), req)
}

// Leave mocks base method.
func (m *MockService) Leave(req *dto.LeaveGroupRequest) (*dto.LeaveGroupResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leave", req)
	ret0, _ := ret[0].(*dto.LeaveGroupResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// Leave indicates an expected call of Leave.
func (mr *MockServiceMockRecorder) Leave(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockService)(nil).Leave), req)
}

// UpdateConfirm mocks base method.
func (m *MockService) UpdateConfirm(req *dto.UpdateConfirmGroupRequest) (*dto.UpdateConfirmGroupResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfirm", req)
	ret0, _ := ret[0].(*dto.UpdateConfirmGroupResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// UpdateConfirm indicates an expected call of UpdateConfirm.
func (mr *MockServiceMockRecorder) UpdateConfirm(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfirm", reflect.TypeOf((*MockService)(nil).UpdateConfirm), req)
}
