// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/selection/selection.handler.go

// Package mock_selection is a generated GoMock package.
package mock_selection

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	router "github.com/isd-sgcu/rpkm67-gateway/internal/router"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// CreateSelection mocks base method.
func (m *MockHandler) CreateSelection(c router.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateSelection", c)
}

// CreateSelection indicates an expected call of CreateSelection.
func (mr *MockHandlerMockRecorder) CreateSelection(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSelection", reflect.TypeOf((*MockHandler)(nil).CreateSelection), c)
}

// DeleteSelection mocks base method.
func (m *MockHandler) DeleteSelection(c router.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteSelection", c)
}

// DeleteSelection indicates an expected call of DeleteSelection.
func (mr *MockHandlerMockRecorder) DeleteSelection(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSelection", reflect.TypeOf((*MockHandler)(nil).DeleteSelection), c)
}

// FindByGroupIdSelection mocks base method.
func (m *MockHandler) FindByGroupIdSelection(c router.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FindByGroupIdSelection", c)
}

// FindByGroupIdSelection indicates an expected call of FindByGroupIdSelection.
func (mr *MockHandlerMockRecorder) FindByGroupIdSelection(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGroupIdSelection", reflect.TypeOf((*MockHandler)(nil).FindByGroupIdSelection), c)
}
