// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/auth/auth.service.go

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apperror "github.com/isd-sgcu/rpkm67-gateway/apperror"
	dto "github.com/isd-sgcu/rpkm67-gateway/internal/dto"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetGoogleLoginUrl mocks base method.
func (m *MockService) GetGoogleLoginUrl() (*dto.GetGoogleLoginUrlResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoogleLoginUrl")
	ret0, _ := ret[0].(*dto.GetGoogleLoginUrlResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetGoogleLoginUrl indicates an expected call of GetGoogleLoginUrl.
func (mr *MockServiceMockRecorder) GetGoogleLoginUrl() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoogleLoginUrl", reflect.TypeOf((*MockService)(nil).GetGoogleLoginUrl))
}

// RefreshToken mocks base method.
func (m *MockService) RefreshToken() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RefreshToken")
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockServiceMockRecorder) RefreshToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockService)(nil).RefreshToken))
}

// Validate mocks base method.
func (m *MockService) Validate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Validate")
}

// Validate indicates an expected call of Validate.
func (mr *MockServiceMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockService)(nil).Validate))
}

// VerifyGoogleLogin mocks base method.
func (m *MockService) VerifyGoogleLogin(req *dto.VerifyGoogleLoginRequest) (*dto.VerifyGoogleLoginResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyGoogleLogin", req)
	ret0, _ := ret[0].(*dto.VerifyGoogleLoginResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// VerifyGoogleLogin indicates an expected call of VerifyGoogleLogin.
func (mr *MockServiceMockRecorder) VerifyGoogleLogin(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyGoogleLogin", reflect.TypeOf((*MockService)(nil).VerifyGoogleLogin), req)
}
