// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/checkin": {
            "post": {
                "description": "Create a check-in using email, event and user_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkin"
                ],
                "summary": "Create a check-in",
                "parameters": [
                    {
                        "description": "Create CheckIn Request",
                        "name": "create",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCheckInRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCheckInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            }
        },
        "/checkin/email/{email}": {
            "get": {
                "description": "Find check-ins by email",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkin"
                ],
                "summary": "Find check-ins by email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FindByEmailCheckInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            }
        },
        "/checkin/{userId}": {
            "get": {
                "description": "Find check-ins by user_id",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkin"
                ],
                "summary": "Find check-ins by user_id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FindByUserIdCheckInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            }
        },
        "/stamp/{userId}": {
            "get": {
                "description": "Find stamp by user id",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stamp"
                ],
                "summary": "Find stamp by user id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FindByUserIdStampResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            },
            "post": {
                "description": "Stamp by user id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stamp"
                ],
                "summary": "Stamp by user id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Stamp by user id request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.StampByUserIdBodyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StampByUserIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            }
        },
        "/count": {
            "post": {
                "description": "Add 1 to count metrics by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "count"
                ],
                "summary": "Count clicks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the count metric",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apperror.AppError": {
            "type": "object",
            "properties": {
                "httpCode": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.CheckIn": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.CountResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.CreateCheckInRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateCheckInResponse": {
            "type": "object",
            "properties": {
                "checkin": {
                    "$ref": "#/definitions/dto.CheckIn"
                }
            }
        },
        "dto.FindByEmailCheckInResponse": {
            "type": "object",
            "properties": {
                "checkins": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CheckIn"
                    }
                }
            }
        },
        "dto.FindByUserIdCheckInResponse": {
            "type": "object",
            "properties": {
                "checkins": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CheckIn"
                    }
                }
            }
        },
        "dto.FindByUserIdStampResponse": {
            "type": "object",
            "properties": {
                "stamp": {
                    "$ref": "#/definitions/dto.Stamp"
                }
            }
        },
        "dto.Stamp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "point_a": {
                    "type": "integer"
                },
                "point_b": {
                    "type": "integer"
                },
                "point_c": {
                    "type": "integer"
                },
                "point_d": {
                    "type": "integer"
                },
                "stamp": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.StampByUserIdBodyRequest": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "type": "string"
                },
                "pin": {
                    "type": "string"
                }
            }
        },
        "dto.StampByUserIdResponse": {
            "type": "object",
            "properties": {
                "stamp": {
                    "$ref": "#/definitions/dto.Stamp"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3001",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "RPKM67 API",
	Description:      "the RPKM67 API server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
