basePath: /api/v1
definitions:
  apperror.AppError:
    properties:
      httpCode:
        type: integer
      id:
        type: string
    type: object
  constant.Role:
    enum:
    - user
    - staff
    type: string
    x-enum-varnames:
    - USER
    - STAFF
  dto.CheckIn:
    properties:
      email:
        type: string
      event:
        type: string
      id:
        type: string
      user_id:
        type: string
    type: object
  dto.CountResponse:
    properties:
      success:
        type: boolean
    type: object
  dto.CreateCheckInRequest:
    properties:
      email:
        type: string
      event:
        type: string
      user_id:
        type: string
    type: object
  dto.CreateCheckInResponse:
    properties:
      checkin:
        $ref: '#/definitions/dto.CheckIn'
    type: object
  dto.Credential:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3BiZX...
        type: string
      expires_in:
        example: 3600
        type: integer
      refresh_token:
        example: e7e84d54-7518-4...
        type: string
    type: object
  dto.FindAllPinResponse:
    properties:
      pins:
        items:
          $ref: '#/definitions/dto.Pin'
        type: array
    type: object
  dto.FindByEmailCheckInResponse:
    properties:
      checkins:
        items:
          $ref: '#/definitions/dto.CheckIn'
        type: array
    type: object
  dto.FindByUserIdCheckInResponse:
    properties:
      checkins:
        items:
          $ref: '#/definitions/dto.CheckIn'
        type: array
    type: object
  dto.FindByUserIdStampResponse:
    properties:
      stamp:
        $ref: '#/definitions/dto.Stamp'
    type: object
  dto.FindOneUserResponse:
    properties:
      user:
        $ref: '#/definitions/dto.User'
    type: object
  dto.GetGoogleLoginUrlResponse:
    properties:
      url:
        type: string
    type: object
  dto.Pin:
    properties:
      activity_id:
        type: string
      code:
        type: string
    type: object
  dto.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.ResetPinResponse:
    properties:
      pin:
        $ref: '#/definitions/dto.Pin'
    type: object
  dto.Stamp:
    properties:
      id:
        type: string
      point_a:
        type: integer
      point_b:
        type: integer
      point_c:
        type: integer
      point_d:
        type: integer
      stamp:
        type: string
      user_id:
        type: string
    type: object
  dto.StampByUserIdBodyRequest:
    properties:
      activity_id:
        type: string
      pin_code:
        type: string
    type: object
  dto.StampByUserIdResponse:
    properties:
      stamp:
        $ref: '#/definitions/dto.Stamp'
    type: object
  dto.UpdateUserPictureResponse:
    properties:
      success:
        type: boolean
    type: object
  dto.UpdateUserProfileBody:
    properties:
      baan:
        type: string
      drug_allergy:
        type: string
      faculty:
        type: string
      firstname:
        type: string
      food_allergy:
        type: string
      group_id:
        type: string
      illness:
        type: string
      lastname:
        type: string
      nickname:
        type: string
      parent:
        type: string
      parent_tel:
        type: string
      receive_gift:
        type: integer
      tel:
        type: string
      title:
        type: string
      year:
        type: integer
    type: object
  dto.UpdateUserProfileResponse:
    properties:
      success:
        type: boolean
    type: object
  dto.User:
    properties:
      baan:
        type: string
      drug_allergy:
        type: string
      email:
        type: string
      faculty:
        type: string
      firstname:
        type: string
      food_allergy:
        type: string
      group_id:
        type: string
      id:
        type: string
      illness:
        type: string
      lastname:
        type: string
      nickname:
        type: string
      parent:
        type: string
      parent_tel:
        type: string
      photo_key:
        type: string
      photo_url:
        type: string
      receive_gift:
        type: integer
      role:
        $ref: '#/definitions/constant.Role'
      stamp:
        $ref: '#/definitions/dto.Stamp'
      tel:
        type: string
      title:
        type: string
      year:
        type: integer
    type: object
  dto.VerifyGoogleLoginResponse:
    properties:
      credential:
        $ref: '#/definitions/dto.Credential'
      user_id:
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: the RPKM67 API server.
  title: RPKM67 API
  version: "1.0"
paths:
  /auth/google-url:
    get:
      description: get google login url
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetGoogleLoginUrlResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Get Google login url
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: get both new access token and refresh token
      parameters:
      - description: refresh token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Credential'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperror.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Refresh access token with refresh token
      tags:
      - auth
  /auth/verify-google:
    get:
      consumes:
      - text/plain
      description: returns user's credential
      parameters:
      - description: Code from google login
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.VerifyGoogleLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperror.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Verify Google login
      tags:
      - auth
  /checkin:
    post:
      consumes:
      - application/json
      description: Create a check-in using email, event and user_id
      parameters:
      - description: Create CheckIn Request
        in: body
        name: create
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCheckInRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateCheckInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      security:
      - BearerAuth: []
      summary: Create a check-in
      tags:
      - checkin
  /checkin/{userId}:
    get:
      consumes:
      - text/plain
      description: Find check-ins by user_id
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FindByUserIdCheckInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      security:
      - BearerAuth: []
      summary: Find check-ins by user_id
      tags:
      - checkin
  /checkin/email/{email}:
    get:
      consumes:
      - text/plain
      description: Find check-ins by email
      parameters:
      - description: Email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FindByEmailCheckInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      security:
      - BearerAuth: []
      summary: Find check-ins by email
      tags:
      - checkin
  /clean-db:
    get:
      description: must be used only in development environment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Credential'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Clean all data in database
      tags:
      - db
  /count:
    post:
      consumes:
      - application/json
      description: Add 1 to count metrics by name
      parameters:
      - description: Name of the count metric
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Count clicks
      tags:
      - count
  /pin:
    get:
      description: Staff only
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FindAllPinResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apperror.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.AppError'
      security:
      - BearerAuth: []
      summary: Find all pins
      tags:
      - pin
  /pin/reset/{activityId}:
    post:
      consumes:
      - text/plain
      description: Staff only
      parameters:
      - description: should be `workshop-1` to `workshop-5`
        in: path
        name: activityId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResetPinResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apperror.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.AppError'
      security:
      - BearerAuth: []
      summary: Reset a pin
      tags:
      - pin
  /stamp/{userId}:
    get:
      consumes:
      - text/plain
      description: Find stamp by user id
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FindByUserIdStampResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      security:
      - BearerAuth: []
      summary: Find stamp by user id
      tags:
      - stamp
    post:
      consumes:
      - application/json
      description: Stamp of activity id by user id
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: 'activity_id is body can ONLY be: `workshop-1` to `workshop-5`,
          `landmark-1` to `landmark-4`, `club-1` to `club-2`'
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.StampByUserIdBodyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.StampByUserIdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      security:
      - BearerAuth: []
      summary: Stamp by user id
      tags:
      - stamp
  /user/{id}:
    get:
      consumes:
      - text/plain
      description: Find user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FindOneUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperror.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.AppError'
      security:
      - BearerAuth: []
      summary: Find user by id
      tags:
      - user
  /user/picture/{id}:
    put:
      consumes:
      - application/json
      description: Updates only field that are in input, used for both user picture
        update
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: image to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateUserPictureResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperror.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.AppError'
      security:
      - BearerAuth: []
      summary: Update user's picture fields by id
      tags:
      - user
  /user/profile/{id}:
    patch:
      consumes:
      - application/json
      description: Updates only field that are in input, used for both user profile
        and update reward status
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: update user request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserProfileBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateUserProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperror.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.AppError'
      security:
      - BearerAuth: []
      summary: Update profile fields of user by id
      tags:
      - user
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
