name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    tags:
      - v*

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: <WILL_BE_SET>

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: dev
          DEFAULT_BUMP: patch
        id: tag_action

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${{ steps.tag_action.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
  
  cd:
    name: Continuous Deployment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DevOps repository
        uses: actions/checkout@v4
        with:
            repository: isd-sgcu/rpkm67-devops
            token: ${{ secrets.DEVOPS_TOKEN }}

      - name: Update image tag
        uses: mikefarah/yq@master
        env:
          NEW_TAG: ${{ env.IMAGE_TAG }}
        with:
          cmd: yq -i '.[0].value = "ghcr.io/isd-sgcu/rpkm67-gateway:" + strenv(NEW_TAG)' isd/rpkm67-gateway/deployment.yaml

      - name: Commit & Push changes
        uses: actions-js/push@v1.4
        with:
          repository: isd-sgcu/rpkm67-devops
          github_token: ${{ secrets.DEVOPS_TOKEN }}
