name: Send Messages

on:
  workflow_call:
    inputs:
      webhook_url:
        description: 'The webhook URL of the Discord channel'
        required: true
        type: string
      discord_api_key:
        description: 'The API key of the Discord bot'
        required: true
        type: string

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
    - name: Send message to Discord
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -H "Authorization: Bot ${{ inputs.discord_api_key }}" \
        -d "{
              \"content\": \"A new push has been made to the **${{ github.event.pull_request.base.ref }}** branch by ${{ github.actor }}!\",
              \"embeds\": [
                {
                  \"author\": {
                    \"name\": \"${{ github.actor }}\",
                    \"icon_url\": \"https://github.com/${{ github.actor }}.png\"
                  },
                  \"description\": \"**Service Name:** ${{ github.repository }}\n\n
                  **Details:**\n
                    ${{ github.event.pull_request.title || '' }}
                  \",
                  \"color\": 5814783
                }
              ]
            }" \
        ${{ inputs.webhook_url }}